version: "2"
services:
  aria2:
    image: superng6/qbittorrentee
    container_name: qbittorrentee
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
    volumes:
      - /path/to/appdata/config:/config
      - /path/to/downloads:/Downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8989:8989
    restart: unless-stopped
